'use strict';
const $ = s => document.querySelector(s);
const esc = value => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const labels = {review:'Нужна проверка',draft:'Черновик',approved:'Подтверждено',paid:'Оплачено',archived:'Архив',suggested:'Есть ответ из базы',needs_agent:'Нужен оператор',ready:'Ответ подготовлен',closed:'Закрыто',confirmed:'Подтверждено',cancelled:'Отменено'};
const badge = s => `<span class="badge ${esc(s)}">${esc(labels[s] || s)}</span>`;
const date = v => v ? new Date(v).toLocaleString('ru-RU',{dateStyle:'medium',timeStyle:'short',timeZone:state?.settings?.timezone||'UTC'}) : '—';
let info, state, view = 'records', search = '', status = '', chosenSlot = '';
async function api(path, body){
 const options = body === undefined ? {} : {method:'POST',headers:{'Content-Type':'application/json','X-Requested-With':'BusinessDesk'},body:JSON.stringify(body)};
 const r = await fetch(path, options); const data = await r.json();
 if(!r.ok){if(r.status===401){info.authenticated=false;renderLogin()}throw new Error(data.error || 'Ошибка запроса')}
 return data;
}
function toast(text){const node=$('#toast');node.textContent=text;node.style.display='block';clearTimeout(toast.timer);toast.timer=setTimeout(()=>node.style.display='none',5000)}
function modal(title,html){$('#modal-content').innerHTML=`<div class="modal-head"><h2>${esc(title)}</h2><button class="close" data-close aria-label="Закрыть">×</button></div><div class="error-box" id="form-error"></div>${html}`;$('#modal').showModal();$('#modal [data-close]').onclick=()=>$('#modal').close()}
function bindForm(id, handler){const form=$(id);form.onsubmit=async e=>{e.preventDefault();const button=form.querySelector('[type=submit]');if(button)button.disabled=true;try{await handler(Object.fromEntries(new FormData(form)),form)}catch(error){const box=$('#form-error')||$('#page-error');if(box)box.textContent=error.message;else toast(error.message)}finally{if(button)button.disabled=false}}}
function field(name,label,type='text',value='',extra=''){return `<label for="f-${name}">${label}</label><input id="f-${name}" name="${name}" type="${type}" value="${esc(value)}" ${extra}>`}
function area(name,label,value='',extra=''){return `<label for="f-${name}">${label}</label><textarea id="f-${name}" name="${name}" ${extra}>${esc(value)}</textarea>`}
function actions(text='Сохранить'){return `<div class="actions"><button type="button" class="secondary" data-cancel>Отмена</button><button type="submit">${text}</button></div>`}
function cancelBind(){const node=$('[data-cancel]');if(node)node.onclick=()=>$('#modal').close()}
async function refresh(){state=await api('/api/dashboard');renderShell()}
function renderLogin(){
 $('#app').innerHTML=`<section class="panel login"><div class="brand"><span class="brand-mark">${info.meta.name[0]}</span>${info.meta.name}</div><span class="eyebrow">Рабочее пространство</span><h1>Добро пожаловать</h1><p class="muted">${esc(info.meta.tagline)}</p><form id="login">${field('password','Пароль администратора','password','','required autocomplete="current-password"')}<div id="page-error" class="error-box"></div><button type="submit">Войти в приложение →</button></form><p class="help">Пароль первого входа находится в файле FIRST-LOGIN.txt в папке данных приложения.</p>${['booking','support'].includes(info.project)?'<a href="/public">Открыть клиентскую страницу →</a>':''}</section>`;
 bindForm('#login',async body=>{await api('/api/login',body);info.authenticated=true;await refresh()});
}
const copy={quote:{title:'Коммерческие предложения',sub:'Согласуйте позиции, проверьте стоимость и подготовьте предложение клиенту.',create:'Новое предложение',extra:'Каталог товаров'},invoice:{title:'Счета под контролем',sub:'От поступления документа до подтверждения и оплаты — в одном месте.',create:'Добавить счёт',extra:null},support:{title:'Центр поддержки',sub:'Проверенные знания для простых вопросов. Личное внимание — для остальных.',create:'Новое обращение',extra:'База знаний'},booking:{title:'Расписание встреч',sub:'Записи без пересечений, календарь и подготовка напоминаний.',create:'Новая запись',extra:'Напоминания'}};
function renderShell(){
 const c=copy[info.project];document.title=info.meta.name;document.documentElement.style.setProperty('--accent',({quote:'#107c78',invoice:'#4661a8',support:'#7954a6',booking:'#ad683a'})[info.project]);
 $('#app').innerHTML=`<div class="shell"><aside class="sidebar"><div class="brand"><span class="brand-mark">${info.meta.name[0]}</span>${info.meta.name}</div><div class="caption">${esc(info.meta.tagline)}</div><button class="nav ${view==='records'?'active':''}" data-view="records">▦ &nbsp; ${info.project==='booking'?'Расписание':'Рабочий стол'}</button>${c.extra?`<button class="nav ${view==='extra'?'active':''}" data-view="extra">▤ &nbsp; ${c.extra}</button>`:''}<button class="nav ${view==='audit'?'active':''}" data-view="audit">◷ &nbsp; Журнал действий</button><button class="nav ${view==='settings'?'active':''}" data-view="settings">⚙ &nbsp; Настройки</button><div class="sidebar-foot">Локальное приложение<br>Ваши данные — на вашем компьютере<br><br>v1.0 · Один бизнес, одна команда</div></aside><div class="workspace"><header class="topbar"><strong>${esc(state.settings.name)}</strong><div class="status-line">${['support','booking'].includes(info.project)?'<a href="/public" target="_blank" rel="noopener">Клиентская страница ↗</a>':''}<span class="pill">Администратор</span><button class="secondary small" id="logout">Выйти</button></div></header>${state.settings.demo?'<div class="demo-strip">ДЕМО · Все имена, документы и обращения вымышлены. Внешние сообщения не отправляются.</div>':''}<main class="content" id="content"></main></div></div>`;
 document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{view=b.dataset.view;renderShell()});$('#logout').onclick=async()=>{await api('/api/logout',{});renderLogin()};
 if(view==='records')renderRecords();if(view==='extra')renderExtra();if(view==='audit')renderAudit();if(view==='settings')renderSettings();
}
function renderRecords(){const c=copy[info.project],rows=state.records;
 let ready=rows.filter(r=>['approved','paid','ready','closed','confirmed'].includes(r.status)).length;
 let review=rows.filter(r=>['review','needs_agent','draft','suggested'].includes(r.status)).length;
 $('#content').innerHTML=`<div class="page-head"><div><div class="eyebrow">${esc(info.meta.name)} / Обзор</div><h1>${c.title}</h1><p class="muted">${c.sub}</p></div><button id="create">＋ ${c.create}</button></div><div class="stats"><div class="stat"><div class="label">Всего ${info.project==='booking'?'записей':'документов и обращений'}</div><div class="value">${rows.length}</div><span class="help">Сохранено в приложении</span></div><div class="stat"><div class="label">${info.project==='booking'?'Подтверждённые':'Готово / подтверждено'}</div><div class="value">${ready}</div><span class="help">${info.project==='booking'?'Включая прошедшие встречи':'Проверено сотрудником'}</span></div><div class="stat"><div class="label">${info.project==='booking'?'Отменённые':'Ожидают решения'}</div><div class="value">${info.project==='booking'?rows.filter(r=>r.status==='cancelled').length:review}</div><span class="help">${info.project==='booking'?'Время доступно для новой записи':'Откройте карточку для проверки'}</span></div></div><section class="panel"><div class="panel-head"><h2>${info.project==='booking'?'Ближайшие и прошедшие встречи':'Последние записи'}</h2><a class="inline-link fine" href="/api/export">Экспорт CSV ↓</a></div><div class="toolbar"><input id="search" placeholder="Поиск по имени, номеру или тексту…" aria-label="Поиск" value="${esc(search)}"><div class="grow"></div><select id="filter" aria-label="Статус"><option value="">Все статусы</option>${[...new Set(rows.map(r=>r.status))].map(s=>`<option value="${s}" ${s===status?'selected':''}>${labels[s]}</option>`).join('')}</select></div><div id="rows"></div></section><p class="help">${info.project==='invoice'?'В экспорт попадают только подтверждённые и оплаченные счета.':info.project==='quote'?'Цены сохраняются в предложении на момент создания. Изменение каталога не меняет старые предложения.':info.project==='support'?'Ответы берутся из опубликованных статей. Поиск по ключевым словам — без генерации AI.':'Время показано в часовом поясе '+esc(state.settings.timezone)+'. Рабочие дни: понедельник–пятница.'}</p>`;
 $('#create').onclick=createForm;$('#search').oninput=e=>{search=e.target.value;renderRows()};$('#filter').onchange=e=>{status=e.target.value;renderRows()};renderRows();
}
function renderRows(){let rows=state.records.filter(r=>(!status||r.status===status)&&JSON.stringify(r).toLowerCase().includes(search.toLowerCase()));
 if(!rows.length){$('#rows').innerHTML='<div class="empty"><strong>Здесь пока нет записей</strong>Создайте первую запись или измените фильтры.</div>';return}
 const p=info.project,head=p==='invoice'?['Поставщик / номер','Сумма','Срок','Статус','']:p==='booking'?['Клиент','Услуга','Начало','Статус','']:p==='quote'?['Клиент','Сумма','Создано','Статус','']:['Клиент','Обращение','Создано','Статус',''];
 $('#rows').innerHTML=`<div class="table-wrap"><table><thead><tr>${head.map(x=>`<th>${x}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>{let cols;if(p==='invoice')cols=[`<strong>${esc(r.fields.vendor||'Не указан')}</strong><div class="muted">${esc(r.fields.number||'Без номера')}</div>`,`${esc(r.fields.total||'—')} ${esc(r.fields.currency)}`,esc(r.fields.due||'—')];else if(p==='booking')cols=[`<strong>${esc(r.customer)}</strong><div class="muted">${esc(r.email)}</div>`,`${esc(r.service)}<div class="muted">${esc(r.resource)}</div>`,esc(date(r.start))];else if(p==='quote')cols=[`<strong>${esc(r.customer)}</strong><div class="muted">${esc(r.email)}</div>`,`${esc(r.total)} ${esc(r.currency)}${r.status==='review'?'<div class="muted">Неполная сумма</div>':''}`,esc(date(r.created))];else cols=[`<strong>${esc(r.customer)}</strong><div class="muted">${esc(r.email)}</div>`,esc(r.question.slice(0,85)),esc(date(r.created))];return `<tr>${cols.map(x=>`<td>${x}</td>`).join('')}<td>${badge(r.status)}</td><td><button class="secondary small" data-open="${r.id}">Открыть →</button></td></tr>`}).join('')}</tbody></table></div>`;
 document.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>detail(b.dataset.open));
}
function createForm(){const p=info.project;if(p==='booking'){bookingForm(false);return}
 let content='';if(p==='quote')content=`<div class="grid2">${field('customer','Клиент','text','','required maxlength="200"')}${field('email','Email','email','','required')}</div>${area('lines','Позиции: артикул,количество','LAMP-01,2\nWIRE-10,1','required')}<p class="help">Одна позиция на строку. Артикулы должны совпадать с каталогом. Неизвестные позиции блокируют подтверждение.</p>${field('discount','Скидка, %','number','0','min="0" max="100" step="0.01"')}`;
 if(p==='invoice')content=`<label>Загрузить текстовый PDF (до 2 МБ)</label><input id="pdf" type="file" accept="application/pdf"><p class="help">Из PDF извлекается текст. Сканированные документы требуют внешнего OCR. Проверьте извлечённые поля вручную.</p>${area('text','Текст счёта','Vendor: North Supply\nInvoice: INV-001\nDate: 2026-09-28\nDue: 2026-10-12\nNet: 100\nTax: 20\nTotal: 120\nCurrency: EUR','required')}<p class="help">Поддерживаются поля с подписями на русском и английском. Нестандартные поля можно исправить после импорта.</p>`;
 if(p==='support')content=`<div class="grid2">${field('customer','Клиент','text','','required')}${field('email','Email','email','','required')}</div>${area('question','Вопрос клиента','','required')}`;
 modal(copy[p].create,`<form id="create-form">${content}${actions(p==='quote'?'Рассчитать предложение':'Сохранить и проверить')}</form>`);cancelBind();
 if(p==='invoice')$('#pdf').onchange=async e=>{try{const file=e.target.files[0];if(!file)return;if(file.size>2000000)throw Error('Лимит PDF — 2 МБ');const buffer=await file.arrayBuffer();let binary='';new Uint8Array(buffer).forEach(n=>binary+=String.fromCharCode(n));const data=await api('/api/pdf',{file:btoa(binary)});$('#f-text').value=data.text;toast('Текст извлечён. Проверьте подписи и значения')}catch(err){$('#form-error').textContent=err.message}};
 bindForm('#create-form',async body=>{const result=await api('/api/create',body);$('#modal').close();await refresh();toast(result.duplicate?'Такой документ уже есть — повтор не создан':'Запись сохранена');detail(result.id)});
}
function detail(id){const r=state.records.find(x=>x.id===id);if(!r)return;const p=info.project;
 if(p==='quote'){
  modal('Предложение',`<article class="quote-sheet"><header><div class="eyebrow">${esc(state.settings.name)}</div><div class="title">Коммерческое предложение</div><p class="muted">№ ${esc(r.id)} · ${esc(date(r.created))}</p>${badge(r.status)}</header><div class="details"><div><strong>${esc(r.customer)}</strong><p>${esc(r.email)}</p></div><div>Валюта: ${esc(r.currency)}<p>Скидка: ${esc(r.discount)}%</p></div></div><table><thead><tr><th>Позиция</th><th>Кол-во</th><th>Цена</th><th>Сумма</th></tr></thead><tbody>${r.lines.map(l=>`<tr><td>${esc(l.name)}<div class="muted">${esc(l.sku)}</div></td><td>${esc(l.quantity)}</td><td>${esc(l.price||'—')}</td><td>${esc(l.subtotal||'—')}</td></tr>`).join('')}</tbody></table><div class="total">Итого: ${esc(r.total)} ${esc(r.currency)}</div><p class="help">${r.status==='review'?'ВНИМАНИЕ: не все позиции найдены. Итог неполный. Создайте исправленное предложение после обновления каталога.':'Налог и доставка не рассчитываются отдельно. Условия согласуются с клиентом.'}</p></article><div class="actions">${r.status==='draft'?'<button data-action="approve">Подтвердить</button>':''}${r.status==='approved'?'<button id="print">Печать / PDF</button>':''}${r.status!=='archived'?'<button class="secondary" data-action="archive">В архив</button>':''}</div>`);
  if($('#print'))$('#print').onclick=()=>window.print();
 } else if(p==='invoice'){
  modal('Проверка счёта',`<div class="status-line"><p>№ ${esc(r.fields.number||'—')}</p>${badge(r.status)}</div><div class="split"><section><h3>Исходный документ</h3><div class="source">${esc(r.source)}</div>${r.problems.length?`<div class="error-box">${r.problems.map(esc).join('<br>')}</div>`:'<div class="notice">Арифметика и обязательные поля проверены. Подтверждение остаётся за вами.</div>'}</section><form id="invoice-form"><div class="grid2">${Object.entries({vendor:'Поставщик',number:'Номер',date:'Дата',due:'Срок оплаты',net:'Без налога',tax:'Налог',total:'Итого',currency:'Валюта'}).map(([k,label])=>field(k,label,['date','due'].includes(k)?'date':'text',r.fields[k],r.status==='paid'?'disabled':'required')).join('')}</div>${r.status!=='paid'?'<div class="actions"><button type="submit" class="secondary">Сохранить исправления</button></div>':''}</form></div><div class="actions">${r.status==='review'&&!r.problems.length?'<button data-action="approve">Подтвердить счёт</button>':''}${r.status==='approved'?'<button data-action="paid">Отметить оплаченным</button>':''}</div>`);
  bindForm('#invoice-form',async fields=>{await api('/api/invoice/save',{id,fields});$('#modal').close();await refresh();detail(id);toast('Исправления сохранены; требуется повторное подтверждение')});
 } else if(p==='support'){
  modal('Обращение клиента',`<p><strong>${esc(r.customer)}</strong> · ${esc(r.email)}</p>${badge(r.status)}<h3>Вопрос</h3><div class="source">${esc(r.question)}</div><h3>Результат поиска в базе</h3><div class="kb-answer">${esc(r.answer)}</div><p class="help">${r.source?'Источник: '+esc(r.source.title):'Однозначный источник не найден — нужен оператор.'}</p><form id="reply-form">${area('reply','Ответ оператора — можно отредактировать',r.reply|| (r.source?r.answer:''),'required')}<div class="actions">${r.status!=='closed'?'<button type="submit">Сохранить ответ</button>':''}${['ready','closed'].includes(r.status)?`<a class="inline-link" href="/api/email?id=${id}">Скачать письмо .eml</a>`:''}${r.status==='ready'?'<button type="button" class="secondary" data-action="close">Закрыть обращение</button>':''}</div><p class="help">Сохранение и закрытие не отправляют письмо. Откройте .eml в почтовом приложении, проверьте и отправьте самостоятельно.</p></form>`);
  bindForm('#reply-form',async body=>{await api('/api/action',{id,action:'reply',...body});$('#modal').close();await refresh();detail(id)});
 } else {
  modal('Детали записи',`<p>${badge(r.status)}</p><h3>${esc(r.customer)}</h3><p>${esc(r.email)}</p><div class="booking-summary"><strong>${esc(r.service)}</strong><p>${esc(date(r.start))} — ${esc(date(r.end))}</p><span>${esc(r.resource)} · ${esc(state.settings.timezone)}</span></div><p>${esc(r.note||'Нет примечания')}</p><div class="actions"><a class="inline-link" href="/api/calendar?id=${id}">Скачать в календарь</a>${r.status==='confirmed'?'<button class="danger" data-action="cancel">Отменить запись</button>':''}</div>`);
 }
 document.querySelectorAll('[data-action]').forEach(b=>b.onclick=async()=>{if(['cancel','archive','paid'].includes(b.dataset.action)&&!confirm('Подтвердить действие?'))return;try{await api('/api/action',{id,action:b.dataset.action});$('#modal').close();await refresh();toast('Изменения сохранены')}catch(e){$('#form-error').textContent=e.message}});
}
function renderExtra(){const p=info.project;
 if(p==='quote'){
  $('#content').innerHTML=`<div class="page-head"><div><div class="eyebrow">Справочник</div><h1>Каталог товаров</h1><p class="muted">Единственный источник цен для новых предложений.</p></div><button id="catalog-edit">Импорт / редактирование</button></div><div class="panel"><table><thead><tr><th>Артикул</th><th>Название</th><th>Цена ${esc(state.settings.currency)}</th></tr></thead><tbody>${state.catalog.map(r=>`<tr><td>${esc(r.sku)}</td><td>${esc(r.name)}</td><td>${esc(r.price)}</td></tr>`).join('')}</tbody></table>${!state.catalog.length?'<div class="empty">Импортируйте каталог CSV для начала работы.</div>':''}</div>`;
  $('#catalog-edit').onclick=()=>{const csv=state.catalog.map(r=>[r.sku,r.name,r.price].map(x=>'"'+String(x).replaceAll('"','""')+'"').join(',')).join('\n');modal('Каталог CSV',`<form id="catalog-form"><div class="notice">Импорт полностью заменяет каталог. Сохранённые предложения не изменятся.</div>${area('csv','CSV с заголовками sku,name,price','sku,name,price\n'+csv,'required')}<label>Или выберите CSV-файл</label><input type="file" id="catalog-file" accept=".csv,text/csv">${actions('Заменить каталог')}</form>`);cancelBind();$('#catalog-file').onchange=async e=>{if(e.target.files[0])$('#f-csv').value=await e.target.files[0].text()};bindForm('#catalog-form',async body=>{await api('/api/catalog',body);$('#modal').close();await refresh();toast('Каталог обновлён')})};
 } else if(p==='support'){
  $('#content').innerHTML=`<div class="page-head"><div><div class="eyebrow">Подтверждённые знания</div><h1>База знаний</h1><p class="muted">Клиент видит только опубликованный текст подходящей статьи.</p></div><button id="new-article">＋ Добавить статью</button></div><div class="articles">${state.articles.map(a=>`<article class="article"><span class="eyebrow">Статья</span><h3>${esc(a.title)}</h3><p>${esc(a.body)}</p><p class="help">Ключевые слова: ${esc(a.keywords)}</p><button class="secondary small" data-edit="${a.id}">Редактировать</button></article>`).join('')}</div>`;
  $('#new-article').onclick=()=>articleForm();document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>articleForm(state.articles.find(a=>a.id===b.dataset.edit)));
 } else if(p==='booking'){
  $('#content').innerHTML=`<div class="page-head"><div><div class="eyebrow">Ближайшие 24 часа</div><h1>Напоминания</h1><p class="muted">Подготовьте письма и отправьте их из своей почты после проверки.</p></div><button id="prepare">Подготовить напоминания</button></div><div class="notice">Письма не отправляются автоматически. Повторная подготовка не создаёт дублей; отменённые записи исключаются.</div><section class="panel"><table><thead><tr><th>Клиент</th><th>Начало</th><th>Состояние</th><th></th></tr></thead><tbody>${state.reminders.map(r=>`<tr><td>${esc(r.customer)}<div class="muted">${esc(r.email)}</div></td><td>${esc(date(r.start))}</td><td>${badge(r.status)}</td><td>${r.status==='draft'?`<a href="/api/email?id=${r.id}">Скачать .eml</a>`:''}</td></tr>`).join('')}</tbody></table>${!state.reminders.length?'<div class="empty">Напоминаний пока нет.</div>':''}</section>`;
  $('#prepare').onclick=async()=>{const r=await api('/api/reminders',{});await refresh();toast('Подготовлено: '+r.created)};
 }
}
function articleForm(a={}){modal(a.id?'Редактировать статью':'Новая статья',`<form id="article-form">${field('title','Заголовок','text',a.title||'','required')}${field('keywords','Ключевые слова и синонимы','text',a.keywords||'','required')}${area('body','Проверенный ответ',a.body||'','required')}<p class="help">Не включайте секреты и персональные данные. Этот текст доступен клиентам.</p>${actions('Опубликовать')}</form>`);cancelBind();bindForm('#article-form',async body=>{await api('/api/article',{...body,id:a.id});$('#modal').close();await refresh()})}
function renderAudit(){$('#content').innerHTML=`<div class="page-head"><div><div class="eyebrow">История изменений</div><h1>Журнал действий</h1><p class="muted">Последние 50 событий. Полная история сохраняется в базе данных.</p></div></div><div class="panel"><table><thead><tr><th>Время</th><th>Запись</th><th>Действие</th></tr></thead><tbody>${state.audit.map(r=>`<tr><td>${esc(date(r.created))}</td><td>${esc(r.record_id)}</td><td>${esc(r.action)}</td></tr>`).join('')}</tbody></table></div>`}
function renderSettings(){const s=state.settings;$('#content').innerHTML=`<div class="page-head"><div><div class="eyebrow">Рабочее пространство</div><h1>Настройки</h1><p class="muted">Название компании, параметры работы и доступ.</p></div></div><div class="grid2"><section class="panel"><h2>Компания</h2><form id="settings-form">${field('name','Название','text',s.name,'required')}${field('currency','Валюта (EUR, USD, GBP, RUB, UAH, PLN, CZK)','text',s.currency,'required')}${info.project==='booking'?`${field('timezone','Часовой пояс IANA, например Europe/Prague','text',s.timezone,'required')}<div class="grid2">${field('open_hour','Начало дня','number',s.open_hour,'min="0" max="22" required')}${field('close_hour','Конец дня','number',s.close_hour,'min="1" max="23" required')}</div>${area('resources','Специалисты: по одному в строке',s.resources.join('\n'),'required')}${area('services','Услуги: название,минуты',Object.entries(s.services).map(([n,m])=>n+','+m).join('\n'),'required')}<p class="help">Длительность услуг: 30, 60, 90 или 120 минут. Понедельник–пятница. Изменение пояса меняет отображение существующих записей, но сохраняет их момент времени.</p>`:''}<div class="form-actions"><button type="submit">Сохранить</button></div></form><div class="error-box" id="page-error"></div></section><section class="panel"><h2>Сменить пароль</h2><form id="password-form">${field('old','Текущий пароль','password','','required autocomplete="current-password"')}${field('new','Новый пароль, минимум 12 символов','password','','required minlength="12" autocomplete="new-password"')}<div class="form-actions"><button type="submit" class="secondary">Изменить пароль</button></div></form><div class="notice">После смены пароля все сеансы завершатся. Храните резервные копии базы в защищённом месте.</div></section></div>`;
 bindForm('#settings-form',async body=>{await api('/api/settings',body);await refresh();toast('Настройки сохранены')});bindForm('#password-form',async body=>{await api('/api/password',body);toast('Пароль изменён. Войдите снова');renderLogin()});
}
function bookingFields(){const s=info.settings;return `<div class="grid2"><div><label for="service">Услуга</label><select id="service" name="service">${Object.entries(s.services).map(([n,m])=>`<option value="${esc(n)}">${esc(n)} · ${m} мин</option>`).join('')}</select></div><div><label for="resource">Специалист</label><select id="resource" name="resource">${s.resources.map(n=>`<option>${esc(n)}</option>`).join('')}</select></div></div>${field('day','Дата','date','','required')}<p class="help">Время в ${esc(s.timezone)} · Пн–Пт, ${s.open_hour}:00–${s.close_hour}:00.</p><div id="slots" class="slot-grid">Выберите дату, чтобы увидеть свободное время.</div><div class="grid2">${field('customer','Ваше имя','text','','required maxlength="200"')}${field('email','Email','email','','required')}</div>${field('note','Примечание (необязательно)')}<label class="check"><input name="consent" type="checkbox" required>Согласен на обработку имени и email для этой записи.</label><div class="honeypot" aria-hidden="true"><input name="website" tabindex="-1" autocomplete="off"></div>`}
function wireSlots(){chosenSlot='';const load=async()=>{chosenSlot='';const day=$('#f-day').value;if(!day)return;try{const slots=await api('/api/public/slots?'+new URLSearchParams({date:day,service:$('#service').value,resource:$('#resource').value}));$('#slots').innerHTML=slots.length?slots.map(s=>`<button type="button" class="slot" data-slot="${s.value}">${s.label}</button>`).join(''):'На эту дату свободного времени нет. Выберите другой день.';document.querySelectorAll('[data-slot]').forEach(b=>b.onclick=()=>{chosenSlot=b.dataset.slot;document.querySelectorAll('[data-slot]').forEach(x=>x.classList.toggle('selected',x===b))})}catch(e){$('#slots').textContent=e.message}};$('#service').onchange=load;$('#resource').onchange=load;$('#f-day').onchange=load}
function bookingForm(isPublic){info.settings=state?.settings||info.settings;const html=`<form id="booking-form">${bookingFields()}<div class="error-box" id="page-error"></div><div class="form-actions"><button type="submit">Подтвердить запись →</button></div></form>`;
 if(isPublic)$('#public-panel').innerHTML=html;else modal('Новая запись',html);wireSlots();bindForm('#booking-form',async body=>{if(!chosenSlot)throw Error('Выберите свободное время');const r=await api(isPublic?'/api/public/book':'/api/create',{...body,start:chosenSlot,consent:body.consent==='on'});if(isPublic){const cancelUrl=location.origin+'/public#cancel='+r.cancel_token;$('#public-panel').innerHTML=`<div class="eyebrow">Готово</div><h2>Вы записаны!</h2><div class="booking-summary">${esc(date(r.start))}<p>${esc(body.service)}</p></div><a class="inline-link" href="/api/public/calendar?token=${encodeURIComponent(r.cancel_token)}">Добавить в календарь ↓</a><p class="muted">Сохраните личную ссылку для отмены записи:</p><input readonly aria-label="Ссылка для отмены" value="${esc(cancelUrl)}"><p class="help">Письмо не отправлено. Подтверждение и ссылка доступны на этой странице.</p><a href="/public">Сделать ещё одну запись</a>`}else{$('#modal').close();await refresh();toast('Запись подтверждена')}})}
function renderPublic(){state={settings:info.settings};const booking=info.project==='booking';if(!booking&&info.project!=='support'){$('#app').innerHTML='<main class="loading">Клиентская страница здесь не предусмотрена. <a href="/">Войти</a></main>';return}
 $('#app').innerHTML=`<main class="public-layout"><div class="brand"><span class="brand-mark">${info.meta.name[0]}</span>${esc(info.settings.name)}</div>${info.settings.demo?'<div class="notice">Демонстрация на вымышленных данных.</div>':''}<div class="hero"><span class="eyebrow">${booking?'Ваше время — в ваших руках':'Мы рядом'}</span><h1>${booking?'Запишитесь на удобное время':'Чем можем помочь?'}</h1><p class="muted">${booking?'Выберите услугу и свободный слот. Подтверждение появится сразу.':'Задайте вопрос. Мы найдём ответ в базе знаний или передадим обращение сотруднику.'}</p></div><section class="panel" id="public-panel"></section><p class="footer-note">${esc(info.meta.name)} · <a href="/">Вход для сотрудников</a></p></main>`;
 if(booking){const params=new URLSearchParams(location.hash.slice(1));if(params.has('cancel')){$('#public-panel').innerHTML='<h2>Отменить запись?</h2><p class="muted">Время снова станет доступно другим клиентам.</p><button id="cancel-booking" class="danger">Подтверждаю отмену</button><div id="page-error" class="error-box"></div>';$('#cancel-booking').onclick=async()=>{try{await api('/api/public/cancel',{token:params.get('cancel')});$('#public-panel').innerHTML='<h2>Запись отменена</h2><a href="/public">Выбрать новое время →</a>'}catch(e){$('#page-error').textContent=e.message}}}else bookingForm(true)}else{
  $('#public-panel').innerHTML=`<form id="ask-form"><div class="grid2">${field('customer','Ваше имя','text','','required')}${field('email','Email для ответа','email','','required')}</div>${area('question','Ваш вопрос','','required maxlength="4000"')}<label class="check"><input type="checkbox" name="consent" required>Согласен на обработку обращения и контактных данных.</label><div class="honeypot" aria-hidden="true"><input name="website" tabindex="-1" autocomplete="off"></div><div id="page-error" class="error-box"></div><div class="form-actions"><button type="submit">Найти ответ →</button></div></form><div id="answer"></div>`;
  bindForm('#ask-form',async body=>{const r=await api('/api/public/ask',{...body,consent:body.consent==='on'});$('#answer').innerHTML=`<h3>${r.source?'Ответ из базы знаний':'Передано оператору'}</h3><div class="kb-answer">${esc(r.answer)}</div><p class="help">${r.source?'Источник: '+esc(r.source.title):'Оператор увидит ваше обращение в рабочем пространстве.'} · № ${esc(r.id)}</p>`});
 }
}
async function init(){try{info=await api('/api/info');document.title=info.meta.name;if(location.pathname==='/public')renderPublic();else if(info.authenticated)await refresh();else renderLogin()}catch(e){$('#app').textContent='Не удалось загрузить приложение: '+e.message}}
init();
